### ISSUE TITLE
File in use after move on Windows 

### ISSUE THREAD

**Issue by Migushthe2nd** [sindresorhus/move-file#11]
I'm having issues where this module is somehow accessing the file after it has been moved (file in use on windows). The first time a file is moved there is no problem, but when I try to move another file and overwrite the previous one I am unable to do so. Restarting the node process fixes this. [This module](https://www.npmjs.com/package/mvdir) doesn't seem to have this issue.

```
[Error: EPERM: operation not permitted, rename 'D:\dir_old\original.jpg' -> 'D:\dir\original.jpg'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'rename',
  path: 'D:\\dir_old\\original.jpg',
  dest: 'D:\\dir\\original.jpg'
}
```

**Comment by sindresorhus** [comment]
Looks more like a permission issue. This is either a problem with your system or Node.js. This package is just calling `fs.renameSync`: https://github.com/sindresorhus/move-file/blob/63bf2f051bb6a885d567928d139be6b2a9e9bfaf/index.js#L53

That other module works because it manually deletes the destination before moving. But that is wrong as if the move fails, the destination is still gone. Renaming guarantees to leave the destination untouched if the move fails.

I would try to reproduce using just `fs.renameSync` and then open a Node.js issue.
